config/routes.rb
Rails.application.routes.draw do
  resources :articles
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show]

  def index
    @articles = Article.all
  end

  def show
  end

  private
  def set_article
    @article = Article.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/index.html.erb
<div class="article my-3">
  <% @articles.each do |article| %>
    <%= link_to article.title, article_path(article), class: "stretched-link" %>
    <p class="article-content"><%= article.content %></p>
  <% end %>
</div>

app/views/articles/show.html.erb
<h1><%= @article.title %></h1>
<hr>
<%= @article.content %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWikinimous</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  </head>

  <body>
    <div class="header d-flex justify-content-between align-items-center border-bottom p-3">
    <p>Wikinimous</p>
    <%= link_to 'New Article', new_article_path %>
    </div>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>